Your code contains statements that may cause harm to the server, the task has been aborted.

Details:

from os import walk
for root, dirs, files in walk("."):  

